// <auto-generated />
using System;
using CarPlates.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarPlates.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231019221920_seeding initial data for lookups tables")]
    partial class seedinginitialdataforlookupstables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarPlates.Models.CarPlate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CarStateId")
                        .HasColumnType("bigint");

                    b.Property<long>("CarTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Letters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numbers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerNationalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarStateId");

                    b.HasIndex("CarTypeId");

                    b.ToTable("CarPlates");
                });

            modelBuilder.Entity("CarPlates.Models.CarState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CarStates");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsDeleted = false,
                            State = "بالحركة"
                        },
                        new
                        {
                            Id = 2L,
                            IsDeleted = false,
                            State = "مرتجع سليم"
                        },
                        new
                        {
                            Id = 3L,
                            IsDeleted = false,
                            State = "سليم"
                        });
                });

            modelBuilder.Entity("CarPlates.Models.CarType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CarTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsDeleted = false,
                            Type = "نقل"
                        },
                        new
                        {
                            Id = 2L,
                            IsDeleted = false,
                            Type = "ملاكي"
                        },
                        new
                        {
                            Id = 3L,
                            IsDeleted = false,
                            Type = "أجرة"
                        },
                        new
                        {
                            Id = 4L,
                            IsDeleted = false,
                            Type = "مقطورة"
                        },
                        new
                        {
                            Id = 5L,
                            IsDeleted = false,
                            Type = "حكومة"
                        },
                        new
                        {
                            Id = 6L,
                            IsDeleted = false,
                            Type = "قطاع عام"
                        },
                        new
                        {
                            Id = 7L,
                            IsDeleted = false,
                            Type = "معدة ثقيلة"
                        },
                        new
                        {
                            Id = 8L,
                            IsDeleted = false,
                            Type = "محافظة"
                        },
                        new
                        {
                            Id = 9L,
                            IsDeleted = false,
                            Type = "دراجة محافظة"
                        },
                        new
                        {
                            Id = 10L,
                            IsDeleted = false,
                            Type = "تحت الطلب"
                        },
                        new
                        {
                            Id = 11L,
                            IsDeleted = false,
                            Type = "مؤقت"
                        },
                        new
                        {
                            Id = 12L,
                            IsDeleted = false,
                            Type = "جرار زراعي"
                        },
                        new
                        {
                            Id = 13L,
                            IsDeleted = false,
                            Type = "مقطورة قطاع عام"
                        },
                        new
                        {
                            Id = 14L,
                            IsDeleted = false,
                            Type = "أتوبيس عام"
                        },
                        new
                        {
                            Id = 15L,
                            IsDeleted = false,
                            Type = "أتوبيس خاص"
                        },
                        new
                        {
                            Id = 16L,
                            IsDeleted = false,
                            Type = "أتوبيس مدارس"
                        },
                        new
                        {
                            Id = 17L,
                            IsDeleted = false,
                            Type = "أتوبيس رحلات"
                        },
                        new
                        {
                            Id = 18L,
                            IsDeleted = false,
                            Type = "تجاري"
                        },
                        new
                        {
                            Id = 19L,
                            IsDeleted = false,
                            Type = "دراجة"
                        },
                        new
                        {
                            Id = 20L,
                            IsDeleted = false,
                            Type = "دراجة أجرة"
                        },
                        new
                        {
                            Id = 21L,
                            IsDeleted = false,
                            Type = "أتوبيس سياحة"
                        },
                        new
                        {
                            Id = 22L,
                            IsDeleted = false,
                            Type = "سياحة"
                        },
                        new
                        {
                            Id = 23L,
                            IsDeleted = false,
                            Type = "مقطورة محافظة"
                        },
                        new
                        {
                            Id = 24L,
                            IsDeleted = false,
                            Type = "دراجة حكومة"
                        },
                        new
                        {
                            Id = 25L,
                            IsDeleted = false,
                            Type = "دراجة قطاع عام"
                        },
                        new
                        {
                            Id = 26L,
                            IsDeleted = false,
                            Type = "مقطورة حكومة"
                        },
                        new
                        {
                            Id = 27L,
                            IsDeleted = false,
                            Type = "ملحقة"
                        });
                });

            modelBuilder.Entity("CarPlates.Models.ExecutedCarState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExecutedCarStates");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsDeleted = false,
                            State = "مرتجع تالف"
                        },
                        new
                        {
                            Id = 2L,
                            IsDeleted = false,
                            State = "مرتجع فاقد بالزوج"
                        },
                        new
                        {
                            Id = 3L,
                            IsDeleted = false,
                            State = "مرتجع فاقد بالفرد"
                        });
                });

            modelBuilder.Entity("CarPlates.Models.ExecutedPlate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CarTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("ExecutedCarStateId")
                        .HasColumnType("bigint");

                    b.Property<int>("ExecutionNumber")
                        .HasColumnType("int");

                    b.Property<int>("ExecutionYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Letters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numbers")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarTypeId");

                    b.HasIndex("ExecutedCarStateId");

                    b.ToTable("ExecutedPlates");
                });

            modelBuilder.Entity("CarPlates.Models.CarPlate", b =>
                {
                    b.HasOne("CarPlates.Models.CarState", "CarState")
                        .WithMany()
                        .HasForeignKey("CarStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarPlates.Models.CarType", "CarType")
                        .WithMany()
                        .HasForeignKey("CarTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarState");

                    b.Navigation("CarType");
                });

            modelBuilder.Entity("CarPlates.Models.ExecutedPlate", b =>
                {
                    b.HasOne("CarPlates.Models.CarType", "CarType")
                        .WithMany()
                        .HasForeignKey("CarTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarPlates.Models.ExecutedCarState", "ExecutedCarState")
                        .WithMany()
                        .HasForeignKey("ExecutedCarStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarType");

                    b.Navigation("ExecutedCarState");
                });
#pragma warning restore 612, 618
        }
    }
}
